export type Field = {key:string;label:string;type?:string;options?:string[];ref?:string;required?:boolean};
export type Definition = {label:string;fields:Field[];statuses:string[]};
const f=(key:string,label:string,type='text',required=false):Field=>({key,label,type,required});
const ref=(key:string,label:string,kind:string,required=false):Field=>({key,label,ref:kind,required});
const select=(key:string,label:string,options:string[]):Field=>({key,label,options});
const project=ref('projectId','โครงการ','projects',true), owner=f('owner','ผู้รับผิดชอบ'), note=f('note','หมายเหตุ','textarea');
const dates=[f('start','วันเริ่ม','date',true),f('end','วันสิ้นสุด','date',true)];
const money=(key:string,label:string)=>f(key,label,'money',true);
export const catalog:Record<string,Definition>={
 customers:{label:'ลูกค้า',statuses:['ลูกค้าใหม่','กำลังคุย','รอเสนอราคา','รอตัดสินใจ','ได้งาน','ไม่ได้งาน'],fields:[f('contact','ผู้ติดต่อ'),f('phone','เบอร์โทร','tel'),f('email','อีเมล','email'),f('address','ที่อยู่','textarea'),f('interest','ประเภทงานที่สนใจ'),money('budget','งบประมาณโดยประมาณ'),f('source','แหล่งที่มา'),owner,f('history','บันทึกการติดต่อ','textarea'),f('followup','นัดติดตาม','date')]},
 quotes:{label:'ใบเสนอราคา',statuses:['ร่าง','ส่งแล้ว','อนุมัติ','ไม่อนุมัติ'],fields:[ref('customerId','ลูกค้า','customers',true),ref('projectId','โครงการ','projects'),f('items','รายการงาน','items',true),money('discount','ส่วนลด'),f('vat','VAT (%)','number',true),f('expiry','วันหมดอายุ','date',true),f('terms','เงื่อนไข','textarea')]},
 contracts:{label:'สัญญา',statuses:['ร่าง','ลงนามแล้ว','สิ้นสุด'],fields:[ref('customerId','ลูกค้า','customers',true),project,money('amount','มูลค่าสัญญา'),...dates,note,f('file','ไฟล์สัญญา','file')]},
 projects:{label:'โครงการ',statuses:['วางแผน','กำลังดำเนินการ','พักงาน','ส่งมอบแล้ว','ยกเลิก'],fields:[ref('customerId','ลูกค้า','customers',true),select('type','ประเภท',['ออกแบบ','ก่อสร้าง','ออกแบบพร้อมก่อสร้าง','รีโนเวต']),f('location','ที่ตั้ง'),owner,money('budget','งบประมาณต้นทุน'),money('amount','มูลค่าสัญญา'),...dates,f('progress','ความคืบหน้า (%)','number',true)]},
 appointments:{label:'นัดหมาย',statuses:['นัดหมายแล้ว','กำลังดำเนินการ','เสร็จแล้ว','ยกเลิก'],fields:[select('type','ประเภท',['พบลูกค้า','สำรวจหน้างาน','ประชุม','ออกแบบ','ก่อสร้าง','ส่งมอบ','อื่น ๆ']),ref('customerId','ลูกค้า','customers'),ref('projectId','โครงการ','projects'),f('start','เวลาเริ่ม','datetime-local',true),f('end','เวลาสิ้นสุด','datetime-local',true),owner,f('location','สถานที่'),note]},
 tasks:{label:'แผนงาน',statuses:['ยังไม่เริ่ม','กำลังดำเนินการ','เสร็จแล้ว','ยกเลิก'],fields:[project,ref('teamId','ทีมช่าง','teams'),owner,...dates,note]},
 teams:{label:'ทีมช่าง',statuses:['พร้อมรับงาน','ไม่พร้อม'],fields:[f('leader','หัวหน้าทีม'),f('phone','เบอร์โทร','tel'),f('specialty','ความถนัด'),f('people','จำนวนคน','number',true),money('rate','ค่าแรงอ้างอิง'),f('unit','หน่วยคิดราคา')]},
 bookings:{label:'คิวช่าง',statuses:['จองแล้ว','กำลังทำงาน','เสร็จแล้ว','ยกเลิก'],fields:[project,ref('teamId','ทีมช่าง','teams',true),...dates,note]},
 materials:{label:'วัสดุ',statuses:['ใช้งาน','เลิกใช้'],fields:[f('category','หมวดหมู่'),f('unit','หน่วย', 'text',true),f('minimum','จุดแจ้งเตือนขั้นต่ำ','number',true),money('cost','ต้นทุนต่อหน่วย')]},
 tools:{label:'เครื่องมือ',statuses:['พร้อมใช้','ยืมอยู่','ซ่อม'],fields:[f('condition','สภาพ'),f('location','สถานที่ปัจจุบัน'),f('borrower','ผู้ยืม'),ref('projectId','โครงการ','projects'),f('start','วันที่ยืม','date'),f('end','กำหนดคืน','date'),note]},
 movements:{label:'เคลื่อนไหววัสดุ',statuses:['บันทึกแล้ว'],fields:[ref('materialId','วัสดุ','materials',true),select('type','ประเภท',['รับเข้า','เบิก','คืน','โอน']),f('quantity','จำนวน','number',true),f('from','ต้นทาง (คลังกลาง หรือรหัสโครงการ)'),f('to','ปลายทาง (คลังกลาง หรือรหัสโครงการ)'),ref('projectId','โครงการ','projects'),note]},
 purchases:{label:'ใบสั่งซื้อ',statuses:['ร่าง','สั่งแล้ว','รับบางส่วน','รับครบ','ยกเลิก'],fields:[ref('vendorId','ผู้ขาย','vendors',true),ref('projectId','โครงการ','projects'),ref('requestId','ใบขอซื้อ','requests'),f('location','จุดรับของ','text',true),f('items','รายการวัสดุ','purchase-items',true),f('expected','คาดว่าจะได้รับ','date',true),note]},
 requests:{label:'ใบขอซื้อ',statuses:['ร่าง','อนุมัติ','ไม่อนุมัติ'],fields:[project,f('details','รายการและจำนวนที่ต้องการ','textarea',true),owner,note]},
 vendors:{label:'ผู้ขาย',statuses:['ใช้งาน','เลิกใช้'],fields:[f('contact','ผู้ติดต่อ'),f('phone','เบอร์โทร','tel'),f('category','หมวดวัสดุ')]},
 income:{label:'รายรับ',statuses:['บันทึกแล้ว','ยกเลิก'],fields:[project,ref('installmentId','งวดชำระ','installments'),f('date','วันที่','date',true),money('amount','จำนวนเงิน'),f('category','หมวดหมู่'),select('channel','ช่องทาง',['โอนธนาคาร','เงินสด','เช็ค']),note,f('file','หลักฐาน','file')]},
 expenses:{label:'รายจ่าย',statuses:['บันทึกแล้ว','ยกเลิก'],fields:[project,f('date','วันที่','date',true),money('amount','จำนวนเงิน'),select('category','หมวดหมู่',['วัสดุ (จ่ายซื้อ ไม่คิดต้นทุนซ้ำ)','ค่าแรง','ผู้รับเหมาช่วง','อื่น ๆ']),select('channel','ช่องทาง',['โอนธนาคาร','เงินสด','เช็ค']),note,f('file','หลักฐาน','file')]},
 installments:{label:'งวดชำระ',statuses:['ใช้งาน','ยกเลิก'],fields:[project,money('amount','จำนวนเงิน'),f('due','วันครบกำหนด','date',true),note]},
 documents:{label:'แบบ & เอกสาร',statuses:['รอตรวจ','ต้องแก้ไข','อนุมัติ'],fields:[project,f('version','เวอร์ชัน','text',true),owner,f('date','วันที่','date',true),note,f('file','ไฟล์เอกสาร','file',true)]},
 reports:{label:'รายงานหน้างาน',statuses:['บันทึกแล้ว'],fields:[project,f('date','วันที่','date',true),f('details','รายละเอียดงาน','textarea',true),f('people','จำนวนคน','number'),f('progress','ความคืบหน้า (%)','number'),f('issues','ปัญหา','textarea'),f('file','รูปหน้างาน','file')]},
 changes:{label:'งานเพิ่ม–ลด',statuses:['รออนุมัติ','อนุมัติ','ไม่อนุมัติ'],fields:[project,money('amount','มูลค่าเพิ่ม–ลด (ติดลบได้)'),f('days','ผลกระทบวันส่งมอบ','number'),note]},
 inspections:{label:'ตรวจงาน & ส่งมอบ',statuses:['รอตรวจ','ต้องแก้ไข','ผ่าน','ส่งมอบแล้ว'],fields:[project,owner,f('due','กำหนดแก้ไข','date'),f('handover','วันที่ส่งมอบ','date'),f('details','เช็กลิสต์ / รายการเก็บงาน','textarea'),f('file','รูป / หลักฐานรับมอบ','file')]},
 warranties:{label:'ประกันงาน',statuses:['อยู่ในประกัน','รับแจ้งซ่อม','กำลังซ่อม','เสร็จแล้ว','หมดประกัน'],fields:[project,...dates,owner,f('details','รายการแจ้งซ่อม','textarea'),note]},
 settings:{label:'ข้อมูลบริษัท',statuses:['ใช้งาน'],fields:[f('address','ที่อยู่','textarea'),f('phone','เบอร์โทร','tel'),f('taxId','เลขประจำตัวผู้เสียภาษี'),f('vat','VAT เริ่มต้น (%)','number'),f('prefix','คำนำหน้าเลขเอกสาร'),f('categories','หมวดงาน วัสดุ และค่าใช้จ่าย','textarea'),f('file','โลโก้','file')]},
 members:{label:'สมาชิกทีม',statuses:['ใช้งาน','พักใช้งาน'],fields:[f('role','บทบาทอ้างอิง'),f('phone','เบอร์โทร','tel'),f('email','อีเมล','email')]},
};
export type Item={name:string;quantity:number;unit:string;price:number;materialId?:string;received?:number};
export type Data=Record<string,string|number|Item[]>;
export type Row={id:string;kind:string;code:string;name:string;status:string;data:Data;createdAt:string;updatedAt:string};
export type Move={materialId:string;location:string;quantity:number;cost:number;projectId:string|null;batch:string};
export const menus=[{key:'home',label:'หน้าหลัก',tabs:['overview','analytics']},{key:'schedule',label:'ตารางงาน & นัดหมาย',tabs:['appointments','tasks']},{key:'customers',label:'ลูกค้า & ใบเสนอราคา',tabs:['customers','quotes','contracts']},{key:'projects',label:'โครงการ',tabs:['projects']},{key:'teams',label:'คิวช่าง',tabs:['teams','bookings']},{key:'stock',label:'สต๊อก & จัดซื้อ',tabs:['materials','tools','movements','purchases','requests','vendors']},{key:'finance',label:'การเงิน',tabs:['finance-overview','income','expenses','installments','costs']},{key:'settings',label:'ตั้งค่า',tabs:['settings','members']}];
export const tabNames:Record<string,string>={overview:'ภาพรวม',analytics:'รายงานภาพรวม','finance-overview':'ภาพรวม',costs:'รายงานต้นทุน',...Object.fromEntries(Object.entries(catalog).map(([k,v])=>[k,v.label]))};
export const baht=(satang:number)=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',maximumFractionDigits:2}).format(satang/100);
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const thaiDate=(value:unknown)=>value?new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',day:'numeric',month:'short',year:'numeric'}).format(new Date(String(value).length===10?`${value}T12:00:00+07:00`:String(value))):'—';
