import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import {unlinkSync,writeFileSync,existsSync} from 'node:fs';
import type {Data,Row,Move} from '../src/lib/catalog';
import {balance,paidFor,projectCost} from '../src/lib/rules';
const testPath=path.resolve(`data/test-${randomUUID()}.db`);
process.env.DATABASE_URL=`file:${testPath}`;
const {db}=await import('../src/lib/db');
const {execute,snapshot}=await import('../src/lib/service');
before(()=>{writeFileSync(testPath,'',{flag:'wx'});execFileSync(process.execPath,['node_modules/prisma/build/index.js','db','push'],{cwd:process.cwd(),env:process.env,stdio:'pipe'});});
after(async()=>{await db.$disconnect();if(existsSync(testPath))unlinkSync(testPath);});
const save=async(kind:string,name:string,data:Data,status?:string)=>execute({requestId:randomUUID(),action:'save',kind,name,data,status});
test('connected workflows, atomic stock, conflicts, money, persistence and idempotency',async()=>{
 const customer=await save('customers','ลูกค้าทดสอบ',{budget:100000});
 const quote=await save('quotes','งานก่อสร้าง',{customerId:customer.id,items:[{name:'งาน',quantity:2,unit:'งาน',price:100000}],discount:0,vat:7,expiry:'2026-12-01'});
 await execute({requestId:randomUUID(),action:'approve',id:quote.id});
 const project=await execute({requestId:randomUUID(),action:'convert',id:quote.id});
 const duplicate=await execute({requestId:randomUUID(),action:'convert',id:quote.id});assert.equal(project.id,duplicate.id);
 assert.equal((await db.record.findUniqueOrThrow({where:{id:project.id}})).kind,'projects');
 const appt=await save('appointments','นัดหน้างาน',{customerId:customer.id,projectId:project.id,type:'สำรวจหน้างาน',start:'2026-09-14T09:00',end:'2026-09-14T10:00'});assert.ok(appt.id);
 await assert.rejects(save('appointments','เวลาผิด',{start:'2026-09-15T10:00',end:'2026-09-14T10:00'}),/วันสิ้นสุด/);
 const team=await save('teams','ทีมทดสอบ',{people:3,rate:50000});
 await save('bookings','คิวหนึ่ง',{projectId:project.id,teamId:team.id,start:'2026-09-14',end:'2026-09-16'});
 await assert.rejects(save('bookings','คิวซ้อน',{projectId:project.id,teamId:team.id,start:'2026-09-16',end:'2026-09-17'}),/คิวซ้อน/);
 const material=await save('materials','ปูน',{unit:'ถุง',minimum:2,cost:10000});
 const vendor=await save('vendors','ผู้ขาย',{});
 const po=await save('purchases','สั่งปูน',{vendorId:vendor.id,location:'คลังกลาง',expected:'2026-09-14',items:[{name:'ปูน',materialId:material.id,quantity:10,unit:'ถุง',price:10000}]},'สั่งแล้ว');
 const receive={requestId:randomUUID(),action:'receive',id:po.id,receipts:[4]};await execute(receive);await execute(receive);
 assert.equal((await db.record.findUniqueOrThrow({where:{id:po.id}})).status,'รับบางส่วน');
 assert.equal(balance((await snapshot()).moves as Move[],material.id,'คลังกลาง'),4);
 await assert.rejects(execute({requestId:randomUUID(),action:'receive',id:po.id,receipts:[7]}),/รับเกิน/);
 await execute({requestId:randomUUID(),action:'receive',id:po.id,receipts:[6]});
 assert.equal((await db.record.findUniqueOrThrow({where:{id:po.id}})).status,'รับครบ');
 assert.equal(((await db.record.findUniqueOrThrow({where:{id:po.id}})).data as Data).items instanceof Array,true);
 const stock=(type:string,quantity:number,from='คลังกลาง',to='คลังกลาง')=>save('movements',type,{materialId:material.id,projectId:project.id,type,quantity,from,to});
 await assert.rejects(stock('เบิก',11),/สต๊อกไม่พอ/);
 await stock('โอน',3,'คลังกลาง','ไซต์ A');
 let state=await snapshot();assert.equal(balance(state.moves as Move[],material.id,'คลังกลาง'),7);assert.equal(balance(state.moves as Move[],material.id,'ไซต์ A'),3);
 await stock('เบิก',4);await stock('คืน',1);
 state=await snapshot();assert.equal(balance(state.moves as Move[],material.id,'คลังกลาง'),4);assert.equal(projectCost(state.rows as unknown as Row[],state.moves as Move[],project.id),30000);
 await save('expenses','จ่ายซื้อปูน',{projectId:project.id,date:'2026-09-14',amount:100000,category:'วัสดุ (จ่ายซื้อ ไม่คิดต้นทุนซ้ำ)',channel:'โอนธนาคาร'});
 state=await snapshot();assert.equal(projectCost(state.rows as unknown as Row[],state.moves as Move[],project.id),30000);
 const inst=await save('installments','งวด 1',{projectId:project.id,amount:100000,due:'2026-09-14'});
 const receipt=await save('income','รับเงินบางส่วน',{projectId:project.id,installmentId:inst.id,amount:30000,date:'2026-09-14',channel:'โอนธนาคาร'});
 state=await snapshot();assert.equal(paidFor(state.rows as unknown as Row[],inst.id),30000);
 await assert.rejects(save('income','รับเกิน',{projectId:project.id,installmentId:inst.id,amount:80000,date:'2026-09-14'}),/ยอดรับเกิน/);
 await execute({requestId:randomUUID(),action:'cancel',id:receipt.id});state=await snapshot();assert.equal(paidFor(state.rows as unknown as Row[],inst.id),0);assert.ok(state.audit.some(a=>a.recordId===receipt.id&&a.action==='cancel'));
 await db.$disconnect();assert.equal((await db.record.findUniqueOrThrow({where:{id:customer.id}})).name,'ลูกค้าทดสอบ');
 const count=await db.record.count();await assert.rejects(save('bookings','อ้างอิงผิด',{projectId:'missing',teamId:team.id,start:'2027-01-01',end:'2027-01-02'}));assert.equal(await db.record.count(),count);
});
