"use client";
import { useEffect, useRef, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useAccountStorage, useCloud } from './account-boundary';
import { dialogKeyboard } from './dialog-keyboard';
import { newProject, progress, projectStatuses, projectTypes, readProjects, readiness, safeProjectUrl, selectProjects, splitTags, writeProjects, type Project } from '@/lib/build-lab-storage';
import styles from './build-lab.module.css';

type Field = { key: string; label: string; type?: string; options?: readonly string[]; required?: boolean };
type Values = Record<string, string | number | boolean>;
const field = (key: string, label: string, type = 'text', required = false): Field => ({ key, label, type, required });
const projectFields: Field[] = [field('name','Project Name','text',true), field('shortDescription','Short Description'), field('description','Long Description / Notes','textarea'), {key:'type',label:'Type',options:projectTypes}, {key:'status',label:'Status',options:projectStatuses}, field('startDate','Start Date','date'),field('targetDate','Target Date','date'),field('autoProgress','Auto progress from checklist','checkbox'),field('manualProgress','Manual Progress (%)','number'),field('repositoryUrl','Repository URL','url'),field('demoUrl','Demo URL','url'),field('documentationUrl','Documentation URL','url'),field('technologies','Technologies (comma separated)'),field('tags','Tags (comma separated)'),field('nextTask','Next Task')];
const sections = {
 tasks: { title:'Checklist', empty:'Break this project into small actionable steps.', fields:[field('title','Title','text',true),field('category','Milestone / category'),{key:'priority',label:'Priority',options:['Low','Medium','High']},field('dueDate','Due Date','date')] },
 milestones: {title:'Milestones',empty:'Mark the next meaningful release or achievement.',fields:[field('title','Title','text',true),field('targetDate','Target Date','date'),field('notes','Notes','textarea')]},
 logs: {title:'Dev Log',empty:'Record progress, decisions, bugs, or breakthroughs here.',fields:[field('title','Title','text',true),field('content','Content','textarea',true),field('tags','Tags (comma separated)')]},
 resources: {title:'Links / Resources',empty:'Keep repositories, references, and documentation together.',fields:[field('name','Name','text',true),field('url','URL','url',true),{key:'type',label:'Resource Type',options:['GitHub Repository','Live Demo','Figma','Documentation','Google Drive','Reference','Other']}]},
};
type Section = keyof typeof sections;
type Editor = { title:string; fields:Field[]; initial:Values; save:(v:Values)=>boolean };
const date = (v:string) => v && Number.isFinite(Date.parse(v)) ? new Intl.DateTimeFormat('en-US',{dateStyle:'medium'}).format(new Date(v.length === 10 ? `${v}T12:00:00` : v)) : 'Not set';
function External({url, children}:{url:string;children:React.ReactNode}) { const href=safeProjectUrl(url); return href ? <a href={href} target="_blank" rel="noopener noreferrer">{children} ↗</a> : null; }
function Tags({items}:{items:string[]}) { return <div className={styles.tags}>{items.map(t=><span key={t}>{t}</span>)}</div>; }
function Meter({project}:{project:Project}) { return <div className={styles.meter}><div><span>Progress{project.autoProgress ? ' · checklist' : ''}</span><strong>{progress(project)}%</strong></div><progress max={100} value={progress(project)} aria-label={`${project.name} progress`}/></div>; }
function EditorDialog({editor,close}:{editor:Editor;close:()=>void}) {
 const [values,setValues]=useState(editor.initial); const [error,setError]=useState(''); const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null; ref.current?.querySelector<HTMLElement>('input,textarea,select')?.focus(); const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;previous?.focus();};},[]);
 function submit(e:FormEvent) { e.preventDefault(); for(const f of editor.fields) { const v=String(values[f.key]??'').trim();if(f.required&&!v){setError(`${f.label} is required.`);return;}if(f.type==='url'&&v&&!safeProjectUrl(v)){setError('Use a complete http:// or https:// URL.');return;} }
 if(values.startDate&&values.targetDate&&String(values.targetDate)<String(values.startDate)){setError('Target Date must be on or after Start Date.');return;}
 if(editor.save(values))close(); else setError('Could not save. Check the message on the page and try again.'); }
 return <div className={styles.backdrop}><div ref={ref} className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="build-editor-title" onKeyDown={e=>dialogKeyboard(e,close)}><div className={styles.row}><h2 id="build-editor-title">{editor.title}</h2><button onClick={close} aria-label="Close editor">×</button></div><form onSubmit={submit}><div className={styles.formGrid}>{editor.fields.map(f=><label key={f.key} className={f.type==='textarea'?styles.wide:undefined}>{f.label}{f.required?' *':''}{f.options?<select value={String(values[f.key]??f.options[0])} onChange={e=>setValues({...values,[f.key]:e.target.value})}>{f.options.map(o=><option key={o}>{o}</option>)}</select>:f.type==='textarea'?<textarea rows={4} value={String(values[f.key]??'')} required={f.required} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>:f.type==='checkbox'?<input type="checkbox" checked={!!values[f.key]} onChange={e=>setValues({...values,[f.key]:e.target.checked})}/>:<input type={f.type??'text'} value={String(values[f.key]??'')} required={f.required} min={f.type==='number'?0:undefined} max={f.type==='number'?100:undefined} disabled={f.key==='manualProgress'&&!!values.autoProgress} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>}</label>)}</div>{error&&<p role="alert">{error}</p>}<div className={styles.actions}><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button" type="submit">Save</button></div></form></div></div>;
}
export default function BuildLab({projectId}:{projectId?:string}) {
 const router = useRouter();
 const storage=useAccountStorage();const cloud=useCloud();
 const [state,setState]=useState<{projects:Project[];error:string}>(()=>{try{return {projects:readProjects(storage),error:''};}catch(e){return{projects:[],error:String(e)};}});
 const [feedback,setFeedback]=useState('');const [editor,setEditor]=useState<Editor|null>(null);
 const [query,setQuery]=useState('');const [status,setStatus]=useState('');const [type,setType]=useState('');const [technology,setTechnology]=useState('');const [sort,setSort]=useState('Recently Updated');const [view,setView]=useState('Grid');
 useEffect(()=>{const refresh=()=>{try{setState({projects:readProjects(storage),error:''});}catch(e){setState(s=>({...s,error:String(e)}));}};window.addEventListener('storage',refresh);return()=>window.removeEventListener('storage',refresh);},[storage]);
 const {projects}=state;const project=projects.find(p=>p.id===projectId);
 function save(next:Project[]) {try{writeProjects(storage,next,projects);setState({projects:next,error:''});setFeedback(cloud?'Saved to account sync queue. See sync status above.':'Saved in this browser.');return true;}catch(e){setState(s=>({...s,error:String(e)}));return false;}}
 function update(p:Project){return save(projects.map(item=>item.id===p.id?{...p,updatedAt:new Date().toISOString()}:item));}
 function editProject(p?:Project) {const value=p??newProject();setEditor({title:p?'Edit Project':'New Project',fields:projectFields,initial:{...Object.fromEntries(projectFields.map(f=>[f.key,value[f.key as keyof Project] as string|number|boolean])),technologies:value.technologies.join(', '),tags:value.tags.join(', ')},save:v=>{
 const next={...value,...v,name:String(v.name).trim(),shortDescription:String(v.shortDescription).trim(),manualProgress:Number(v.manualProgress)||0,technologies:splitTags(String(v.technologies)),tags:splitTags(String(v.tags)),updatedAt:new Date().toISOString()} as Project;
 return p?update(next):save([...projects,next]);}});}
 function editItem(section:Section,id?:string) {if(!project)return;const p=project;const existing=p[section].find(i=>i.id===id);const defaults:Values={title:'',name:'',category:'',priority:'Medium',dueDate:'',targetDate:'',notes:'',content:'',tags:'',url:'',type:'Other'};
 const initial={...defaults,...existing,tags:existing&&'tags'in existing?existing.tags.join(', '):''} as Values;
 setEditor({title:`${id?'Edit':'Add'} ${sections[section].title}`,fields:sections[section].fields,initial,save:v=>{const common={id:id??crypto.randomUUID(),projectId:p.id};const str=(key:string)=>String(v[key]??'').trim();const next={...p};
 if(section==='tasks'){const old=p.tasks.find(t=>t.id===id);const item={...common,title:str('title'),category:str('category'),priority:str('priority'),dueDate:str('dueDate'),completed:old?.completed??false,order:old?.order??p.tasks.length};next.tasks=id?p.tasks.map(t=>t.id===id?item:t):[...p.tasks,item];}
 if(section==='milestones'){const old=p.milestones.find(t=>t.id===id);const item={...common,title:str('title'),targetDate:str('targetDate'),notes:str('notes'),completed:old?.completed??false};next.milestones=id?p.milestones.map(t=>t.id===id?item:t):[...p.milestones,item];}
 if(section==='logs'){const old=p.logs.find(t=>t.id===id);const item={...common,title:str('title'),content:str('content'),tags:splitTags(str('tags')),createdAt:old?.createdAt??new Date().toISOString()};next.logs=id?p.logs.map(t=>t.id===id?item:t):[item,...p.logs];}
 if(section==='resources'){const item={...common,name:str('name'),url:str('url'),type:str('type')};next.resources=id?p.resources.map(t=>t.id===id?item:t):[...p.resources,item];}
 return update(next);}});}
 function removeItem(section:Section,id:string) {if(!project||!window.confirm('Delete this item?'))return;update({...project,[section]:project[section].filter(i=>i.id!==id)});}
 function portfolioEditor() {if(!project)return;const p=project;setEditor({title:'Portfolio Info',fields:[field('resumeTitle','Resume Title'),field('summary','One-line Summary'),field('role','Role'),field('technologies','Key Technologies (comma separated)'),field('result','Key Result / Achievement','textarea'),field('includeInResume','Include in Resume','checkbox'),field('presentable','Project is presentable','checkbox')],initial:{...p.portfolio,technologies:p.portfolio.technologies.join(', '),includeInResume:p.includeInResume,presentable:p.presentable},save:v=>update({...p,includeInResume:!!v.includeInResume,presentable:!!v.presentable,portfolio:{resumeTitle:String(v.resumeTitle).trim(),summary:String(v.summary).trim(),role:String(v.role).trim(),technologies:splitTags(String(v.technologies)),result:String(v.result).trim()}})});}
 const visible=selectProjects(projects,query,status,type,technology,sort);
 return <div className={`content ${styles.lab}`}><header className={styles.heading}><div><span className="section-kicker">YOUR PROJECT HUB</span><h2>Build Lab</h2><p>Track everything you build.</p></div><div className={styles.actions}>{projectId?<Link className="secondary-button" href="/build-lab">← All projects</Link>:<button className="primary-button" onClick={()=>editProject()}>+ New Project</button>}<Link href="/" className="secondary-button">Workspace</Link></div></header>
 {state.error&&<p role="alert" className={styles.notice}>{state.error}</p>}{feedback&&<p role="status" className={styles.notice}>{feedback}</p>}
 {projectId ? project ? <>
 <section className={styles.card}><div className={styles.row}><div><div className={styles.tags}><span>{project.type}</span><span>{project.status}</span>{project.includeInResume&&<span>Include in Resume</span>}</div><h1>{project.name}</h1></div><div className={styles.actions}><button className="secondary-button" onClick={()=>editProject(project)}>Edit Project</button><button className="secondary-button" onClick={()=>{if(window.confirm(`Delete “${project.name}” and all its tasks, logs, and resources?`)&&save(projects.filter(p=>p.id!==project.id)))router.push('/build-lab');}}>Delete Project</button></div></div><p>{project.shortDescription}</p><p className={styles.prose}>{project.description}</p><Tags items={project.technologies}/><Tags items={project.tags}/><Meter project={project}/><div className={styles.metadata}><span>Start: {date(project.startDate)}</span><span>Target: {date(project.targetDate)}</span><span>Updated: {date(project.updatedAt)}</span></div><p><strong>Next task: </strong>{project.nextTask||project.tasks.find(t=>!t.completed)?.title||'Set the next step'}</p><div className={styles.actions}><External url={project.repositoryUrl}>GitHub</External><External url={project.demoUrl}>Demo</External><External url={project.documentationUrl}>Documentation</External></div></section>
 <div className={styles.detailGrid}>{(Object.keys(sections) as Section[]).map(section=><section key={section} className={styles.card}><div className={styles.row}><h2>{sections[section].title}</h2><button className="secondary-button" onClick={()=>editItem(section)}>+ Add</button></div>{!project[section].length&&<p className={styles.empty}>{sections[section].empty}</p>}{[...project[section]].sort((a,b)=>'createdAt'in a&&'createdAt'in b?b.createdAt.localeCompare(a.createdAt):'order'in a&&'order'in b?a.order-b.order:0).map(item=><article className={styles.item} key={item.id}><div className={styles.row}><div className={styles.itemTitle}>{'completed'in item&&<input aria-label={`Complete ${item.title}`} type="checkbox" checked={item.completed} onChange={()=>{if(section==='tasks')update({...project,tasks:project.tasks.map(t=>t.id===item.id?{...t,completed:!t.completed}:t)});else update({...project,milestones:project.milestones.map(t=>t.id===item.id?{...t,completed:!t.completed}:t)});}}/>}<strong>{'name'in item?<External url={item.url}>{item.name}</External>:item.title}</strong></div><div className={styles.actions}><button onClick={()=>editItem(section,item.id)}>Edit</button><button onClick={()=>removeItem(section,item.id)}>Delete</button></div></div>{'priority'in item&&<small>{item.priority} priority {item.category&&`· ${item.category}`} {item.dueDate&&`· Due ${date(item.dueDate)}`}</small>}{'targetDate'in item&&<><small>Target: {date(item.targetDate)}</small><p className={styles.prose}>{item.notes}</p></>}{'content'in item&&<><small>{date(item.createdAt)} · {new Date(item.createdAt).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'})}</small><p className={styles.prose}>{item.content}</p><Tags items={item.tags}/></>}{'url'in item&&<><small>{item.type}</small><p className={styles.url}>{item.url}</p></>}</article>)}</section>)}
 <section className={styles.card}><div className={styles.row}><h2>Resume Readiness</h2><strong>{readiness(project).filter(([,ok])=>ok).length} / 6</strong></div>{readiness(project).map(([label,ok])=><p key={label}>{ok?'✓':'○'} {label}</p>)}<p>{safeProjectUrl(project.demoUrl)?'✓':'○'} Demo link (optional)</p><label className={styles.itemTitle}><input type="checkbox" checked={project.includeInResume} onChange={e=>update({...project,includeInResume:e.target.checked})}/>Include in Resume</label><label className={styles.itemTitle}><input type="checkbox" checked={project.presentable} onChange={e=>update({...project,presentable:e.target.checked})}/>Project is presentable</label></section>
 <section className={styles.card}><div className={styles.row}><h2>Portfolio Info</h2><button className="secondary-button" onClick={portfolioEditor}>Edit</button></div><dl>{[['Resume Title',project.portfolio.resumeTitle],['One-line Summary',project.portfolio.summary],['Role',project.portfolio.role],['Key Technologies',project.portfolio.technologies.join(', ')],['Key Result / Achievement',project.portfolio.result]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Not set'}</dd></div>)}</dl></section></div>
 </>:<section className={styles.card}><h2>Project not found</h2><p>The project may have been deleted, or may belong to another account. Check the sync status above.</p></section>:<>
 <div className={styles.summary}>{[['Total Projects',projects.length],['In Progress',projects.filter(p=>p.status==='In Progress').length],['Completed',projects.filter(p=>p.status==='Completed').length],['On Hold',projects.filter(p=>p.status==='On Hold').length]].map(([label,count])=><section key={label} className={styles.card}><small>{label}</small><strong>{count}</strong></section>)}</div>
 <section className={styles.toolbar} aria-label="Search and filter projects"><label>Search<input type="search" placeholder="Search projects, tags, technologies…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{[{label:'Status',value:status,set:setStatus,options:projectStatuses},{label:'Type',value:type,set:setType,options:projectTypes},{label:'Technology',value:technology,set:setTechnology,options:[...new Set(projects.flatMap(p=>p.technologies))].sort()}].map(f=><label key={f.label}>{f.label}<select value={f.value} onChange={e=>f.set(e.target.value)}><option value="">All {f.label.toLowerCase()}</option>{f.options.map(o=><option key={o}>{o}</option>)}</select></label>)}<label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}>{['Recently Updated','Progress','Created Date','Project Name'].map(o=><option key={o}>{o}</option>)}</select></label><div className={styles.actions}>{['Grid','List'].map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v}</button>)}</div></section>
 <p className={styles.muted}>{visible.length} of {projects.length} projects · {cloud?'Account workspace':'Stored in this browser'}</p>
 {!visible.length&&<section className={`${styles.card} ${styles.empty}`}><h2>{projects.length?'No matching projects':'Start tracking something you’re building.'}</h2>{projects.length?<button className="secondary-button" onClick={()=>{setQuery('');setStatus('');setType('');setTechnology('');}}>Clear filters</button>:<button className="primary-button" onClick={()=>editProject()}>+ New Project</button>}</section>}
 <div className={view==='Grid'?styles.grid:styles.list}>{visible.map(p=><article key={p.id} className={`${styles.card} ${styles.projectCard}`}><div className={styles.tags}><span>{p.type}</span><span>{p.status}</span></div><h2><Link href={`/build-lab/${encodeURIComponent(p.id)}`}>{p.name}</Link></h2><p>{p.shortDescription||'Add a short description.'}</p><Tags items={p.technologies}/><Meter project={p}/><p><strong>Next: </strong>{p.nextTask||p.tasks.find(t=>!t.completed)?.title||'Set the next step'}</p><small>Updated {date(p.updatedAt)} · Resume {readiness(p).filter(([,ok])=>ok).length}/6</small><div className={styles.actions}><External url={p.repositoryUrl}>GitHub</External><External url={p.demoUrl}>Live demo</External><button onClick={()=>editProject(p)}>Edit</button></div></article>)}</div>
 </>}{editor&&<EditorDialog editor={editor} close={()=>setEditor(null)}/>}</div>;
}
