"use client";
import { useContext, useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { applicationStatuses, careerDefaults, careerReadiness, completion, projectChecks, projectStatus, readCareer, resumeChecks, safeCareerUrl, skillGroups, skillLevels, writeCareer, type CareerData, type CareerSection } from "@/lib/career-storage";
import { dayKey } from "@/lib/calendar";
import type { Task } from "@/lib/types";
import { TaskContext, TaskControls } from "./task-controls";
import { useCloud } from "./account-boundary";
import { dialogKeyboard } from "./dialog-keyboard";
import styles from "./career-view.module.css";

type Tab = "Overview" | "Applications" | "Resume" | "Portfolio" | "Skills";
type Editable = Exclude<CareerSection, "interview">;
type Editor = { baseline: string; section: Editable; id?: string; values: Record<string, string> };
const fields: Record<Editable, { key: string; label: string; required?: boolean; options?: readonly string[]; type?: string }[]> = {
  goal: [{ key: "title", label: "Career goal", required: true }, { key: "roles", label: "Target roles", required: true }],
  applications: [{ key: "company", label: "Company", required: true }, { key: "position", label: "Position", required: true }, { key: "status", label: "Status", options: applicationStatuses }, { key: "deadline", label: "Deadline", type: "date" }, { key: "link", label: "Application link", type: "url" }, { key: "location", label: "Location (optional)" }, { key: "notes", label: "Notes" }],
  projects: [{ key: "name", label: "Project name", required: true }, { key: "link", label: "GitHub / project link", type: "url" }],
  skills: [{ key: "name", label: "Skill name", required: true }, { key: "group", label: "Group", options: skillGroups }, { key: "level", label: "Level", options: skillLevels }],
  resume: [{ key: "name", label: "Version name", required: true }, { key: "status", label: "Resume status", options: ["Draft", "In review", "Ready"] }, { key: "link", label: "Resume / file link", type: "url" }],
};
function initial(scope: string) { try { return { data: readCareer(localStorage, scope), error: "" }; } catch (error) { return { data: careerDefaults(), error: error instanceof Error ? error.message : "อ่านข้อมูลไม่สำเร็จ" }; } }
function Link({ value, children }: { value: string; children: ReactNode }) { const href = safeCareerUrl(value); return href ? <a href={href} target="_blank" rel="noopener noreferrer">{children} ↗</a> : null; }
export default function CareerView({ tasks, onCreateTask, children }: { tasks: Task[]; onCreateTask: () => void; children: ReactNode }) {
  const cloud = useCloud();
  const scope = cloud?.key ?? "amaris";
  const [state, setState] = useState(() => initial(scope));
  const [tab, setTab] = useState<Tab>("Overview");
  const [status, setStatus] = useState("All");
  const [editor, setEditor] = useState<Editor | null>(null);
  const [deleting, setDeleting] = useState<{ section: Exclude<Editable, "goal">; id: string; name: string } | null>(null);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const origin = useRef<HTMLElement | null>(null);
  const actions = useContext(TaskContext);
  const data = state.data;
  const ready = careerReadiness(data);
  useEffect(() => { const refresh = (event: StorageEvent) => { if (!event.key || event.key.startsWith(`${scope}.career.`)) setState(initial(scope)); }; window.addEventListener("storage", refresh); return () => window.removeEventListener("storage", refresh); }, [scope]);
  function save<K extends CareerSection>(section: K, next: CareerData[K]) {
    try { if (state.error) throw new Error(state.error); writeCareer(localStorage, scope, section, next, data[section]); setState({ data: { ...data, [section]: next }, error: "" }); setError(""); setNotice("บันทึกแล้วในเบราว์เซอร์นี้"); return true; }
    catch (problem) { setError(problem instanceof Error ? problem.message : "บันทึกไม่สำเร็จ กรุณาตรวจพื้นที่จัดเก็บ"); return false; }
  }
  function open(section: Editable, item?: { id?: string; [key: string]: unknown }) { origin.current = document.activeElement as HTMLElement; setError(""); const source = section === "goal" ? data.goal : item; setEditor({ baseline: JSON.stringify(data[section]), section, id: item?.id, values: Object.fromEntries(fields[section].map((field) => [field.key, typeof source?.[field.key as keyof typeof source] === "string" ? String(source![field.key as keyof typeof source]) : field.options?.[0] ?? ""])) }); }
  function close() { setEditor(null); setDeleting(null); setError(""); origin.current?.focus(); }
  function submit(event: FormEvent) {
    event.preventDefault(); if (!editor) return;
    if (editor.baseline !== JSON.stringify(data[editor.section])) { setError("This section changed in another tab. Close and reopen the editor to use the latest data."); return; }
    const v = Object.fromEntries(Object.entries(editor.values).map(([key, value]) => [key, value.trim()]));
    if (fields[editor.section].some((field) => field.required && !v[field.key])) { setError("กรอกข้อมูลที่จำเป็นให้ครบ"); return; }
    if (v.link && !safeCareerUrl(v.link)) { setError("ใช้ลิงก์ http:// หรือ https:// เท่านั้น"); return; }
    const id = editor.id ?? crypto.randomUUID(); const old = editor.section === "goal" ? null : data[editor.section].find((item) => item.id === id);
    let ok = false;
    if (editor.section === "goal") ok = save("goal", { title: v.title, roles: v.roles });
    if (editor.section === "applications") ok = save("applications", [...data.applications.filter((item) => item.id !== id), { id, company: v.company, position: v.position, status: v.status as CareerData["applications"][number]["status"], deadline: v.deadline, link: v.link, location: v.location, notes: v.notes, sample: false }]);
    if (editor.section === "projects") ok = save("projects", [...data.projects.filter((item) => item.id !== id), { id, name: v.name, link: v.link, checks: old && "checks" in old ? old.checks : Array(5).fill(false), sample: false }]);
    if (editor.section === "skills") ok = save("skills", [...data.skills.filter((item) => item.id !== id), { id, name: v.name, group: v.group, level: v.level as CareerData["skills"][number]["level"] }]);
    if (editor.section === "resume") ok = save("resume", [...data.resume.filter((item) => item.id !== id), { id, name: v.name, status: v.status as CareerData["resume"][number]["status"], link: v.link, checks: old && "checks" in old ? old.checks : Array(5).fill(false), updatedAt: new Date().toISOString() }]);
    if (ok) close();
  }
  function remove(section: Exclude<Editable, "goal">, id: string, name: string) { origin.current = document.activeElement as HTMLElement; setError(""); setDeleting({ section, id, name }); }
  function editButtons(section: Exclude<Editable, "goal">, item: { id: string; [key: string]: unknown }, name: string) { return <div className={styles.actions}><button className="text-button" onClick={() => open(section, item)}>Edit</button><button className="text-button" onClick={() => remove(section, item.id, name)}>Delete</button></div>; }
  const upcoming = tasks.filter((task) => task.team === "Career" && !task.deletedAt && task.status !== "Done").sort((a, b) => (a.deadline || "9999").localeCompare(b.deadline || "9999")).slice(0, 5);
  const deadlines = data.applications.filter((app) => app.deadline && !["Rejected", "Offer"].includes(app.status)).sort((a, b) => a.deadline.localeCompare(b.deadline)).slice(0, 5);
  const visible = (section: Tab) => tab === "Overview" || tab === section;
  return <div className={`content ${styles.page}`}><section className={styles.hero}><div><span className="section-kicker">CAREER / INTERNSHIP</span><h2>{data.goal.title}</h2><p>{data.goal.roles}</p><button className="text-button" onClick={() => open("goal")}>Edit goal ↗</button></div><div className={styles.readiness}><strong>{ready.total}% <small>ready</small></strong><progress value={ready.total} max={100} aria-label="Career readiness" /><p>{ready.readyProjects} portfolio projects ready · {ready.coveredSkills}/{data.skills.length} core skills covered</p><details><summary>How readiness is calculated</summary><p>Resume {ready.resume}% + Portfolio {ready.portfolio}% + Skills {ready.skills}% + Applications {ready.applications}% หาร 4 · Applications นับรายการที่ส่งสมัครแล้ว รวมผล Rejected · เป็นความคืบหน้าการเตรียมตัว ไม่ใช่โอกาสได้งาน</p></details></div></section><p className={styles.storage}>ข้อมูล Career บันทึกในเบราว์เซอร์นี้{cloud ? " แยกตามบัญชี" : ""} · ยังไม่ซิงก์ข้ามอุปกรณ์ · รายการ Sample เป็นตัวอย่างที่แก้/ลบได้</p>
    {state.error && <div role="alert" className={styles.error}>{state.error} <button onClick={() => setState(initial(scope))}>โหลดอีกครั้ง</button></div>}{error && !editor && !deleting && <div role="alert" className={styles.error}>{error} <button onClick={() => { setState(initial(scope)); setError(""); }}>โหลดข้อมูลล่าสุด</button></div>}<div role="status" className={styles.notice}>{notice}</div>
    <nav className={styles.tabs} aria-label="Career sections">{(["Overview", "Applications", "Resume", "Portfolio", "Skills"] as Tab[]).map((item) => <button key={item} aria-pressed={tab === item} onClick={() => setTab(item)}>{item}</button>)}</nav>
    <fieldset disabled={!!state.error} className={styles.body}>
    {tab === "Overview" && <section className="panel"><div className="panel-heading"><div><span className="eyebrow">NEXT SMALL MOVES</span><h3>Upcoming Career Actions</h3></div><button className="primary-button" onClick={onCreateTask}>+ Career task</button></div>{!upcoming.length && <p className={styles.empty}>ยังไม่มีงาน Career · เพิ่มงานเตรียม Resume หรือสัมภาษณ์ได้เลย</p>}{upcoming.map((task) => <div key={task.id} className={styles.task}><button className="text-button" onClick={() => actions.edit(task)}>{task.title}</button><small>{task.deadline || "No deadline"}{task.deadline && task.deadline < dayKey(new Date()) ? " · Overdue" : ""}</small><TaskControls task={task} /></div>)}{!!deadlines.length && <div className={styles.deadlines}><span className="eyebrow">APPLICATION DEADLINES</span>{deadlines.map((app) => <button key={app.id} onClick={() => { setTab("Applications"); open("applications", app); }}>{app.deadline} · {app.company} / {app.position}</button>)}</div>}</section>}
    {visible("Applications") && <section className="panel"><div className="panel-heading"><div><span className="eyebrow">YOUR OPPORTUNITIES</span><h3>Applications</h3></div><button className="secondary-button" onClick={() => open("applications")}>+ Add application</button></div><label className={styles.filter}>Filter status<select value={status} onChange={(e) => setStatus(e.target.value)}><option>All</option>{applicationStatuses.map((item) => <option key={item}>{item}</option>)}</select></label><div className={styles.applications}>{data.applications.filter((app) => status === "All" || app.status === status).map((app) => <article key={app.id} className={styles.application}><div><h4>{app.company} {app.sample && <span className={styles.badge}>Sample</span>}</h4><p>{app.position}</p><small>{app.deadline ? `Due ${app.deadline}` : "No deadline"}{app.location && ` · ${app.location}`}</small>{app.notes && <p className={styles.notes}>{app.notes}</p>}<Link value={app.link}>Application link</Link></div><div><select aria-label={`${app.company} status`} value={app.status} onChange={(e) => save("applications", data.applications.map((item) => item.id === app.id ? { ...item, status: e.target.value as typeof app.status, sample: false } : item))}>{applicationStatuses.map((item) => <option key={item}>{item}</option>)}</select>{editButtons("applications", app, app.company)}</div></article>)}</div>{!data.applications.some((app) => status === "All" || app.status === status) && <p className={styles.empty}>No applications here yet</p>}</section>}
    {visible("Resume") && <section className="panel"><div className="panel-heading"><div><span className="eyebrow">TELL YOUR STORY</span><h3>Resume Hub</h3></div><button className="secondary-button" onClick={() => open("resume")}>+ Resume version</button></div><div className={styles.cards}>{data.resume.map((resume) => <article key={resume.id} className={styles.card}><div className={styles.cardHeading}><h4>{resume.name}</h4><span className={styles.badge}>{resume.status}</span></div><small>Last updated: {resume.updatedAt && Number.isFinite(Date.parse(resume.updatedAt)) ? new Date(resume.updatedAt).toLocaleDateString("th-TH") : "Not updated yet"}</small><progress max={100} value={completion(resume.checks)} aria-label={`${resume.name} resume completion`} /><p>{completion(resume.checks)}% complete</p>{resumeChecks.map((label, i) => <label className={styles.check} key={label}><input type="checkbox" checked={resume.checks[i]} onChange={() => save("resume", data.resume.map((item) => item.id === resume.id ? { ...item, updatedAt: new Date().toISOString(), checks: item.checks.map((value, index) => index === i ? !value : value) } : item))} />{label}</label>)}<Link value={resume.link}>Open resume</Link>{!resume.link && <small>เพิ่มลิงก์เอกสารผ่าน Edit</small>}{editButtons("resume", resume, resume.name)}</article>)}</div>{!data.resume.length && <p className={styles.empty}>Add your first resume version</p>}</section>}
    {visible("Portfolio") && <section className="panel"><div className="panel-heading"><div><span className="eyebrow">PROOF OF YOUR WORK</span><h3>Portfolio readiness</h3></div><button className="secondary-button" onClick={() => open("projects")}>+ Add project</button></div><div className={styles.cards}>{data.projects.map((project) => <article key={project.id} className={styles.card}><div className={styles.cardHeading}><h4>{project.name}</h4><span className={styles.badge}>{projectStatus(project)}</span></div>{project.sample && <small>Sample · ปรับ checklist ให้ตรงกับผลงานจริง</small>}<progress max={5} value={project.checks.filter(Boolean).length} aria-label={`${project.name} readiness`} /><p>{project.checks.filter(Boolean).length}/5 complete</p>{projectChecks.map((label, i) => <label key={label} className={styles.check}><input type="checkbox" checked={project.checks[i]} onChange={() => save("projects", data.projects.map((item) => item.id === project.id ? { ...item, sample: false, checks: item.checks.map((value, index) => index === i ? !value : value) } : item))} />{label} available / ready</label>)}<Link value={project.link}>Open project</Link>{editButtons("projects", project, project.name)}</article>)}</div>{!data.projects.length && <p className={styles.empty}>Add a project to prepare your portfolio</p>}</section>}
    {visible("Skills") && <section className="panel"><div className="panel-heading"><div><span className="eyebrow">BUILD YOUR FOUNDATION</span><h3>Skill gaps · {ready.coveredSkills}/{data.skills.length} core skills</h3></div><button className="secondary-button" onClick={() => open("skills")}>+ Add skill</button></div><div className={styles.cards}>{[...new Set(data.skills.map((skill) => skill.group))].map((group) => <div className={styles.card} key={group}><h4>{group}</h4>{data.skills.filter((skill) => skill.group === group).map((skill) => <div className={styles.skill} key={skill.id}><strong>{skill.name}</strong><select aria-label={`${skill.name} level`} value={skill.level} onChange={(e) => save("skills", data.skills.map((item) => item.id === skill.id ? { ...item, level: e.target.value as typeof skill.level } : item))}>{skillLevels.map((level) => <option key={level}>{level}</option>)}</select>{editButtons("skills", skill, skill.name)}</div>)}</div>)}</div>{!data.skills.length && <p className={styles.empty}>Add skills for your target roles</p>}</section>}
    {tab === "Overview" && <section className="panel"><div className="panel-heading"><div><span className="eyebrow">PRACTICE BEFORE THE DAY</span><h3>Interview Prep</h3></div><strong>{completion(data.interview.map((item) => item.done))}%</strong></div><progress max={data.interview.length || 1} value={data.interview.filter((item) => item.done).length} aria-label="Interview preparation" /><div className={styles.interview}>{data.interview.map((topic) => <label className={styles.check} key={topic.id}><input type="checkbox" checked={topic.done} onChange={() => save("interview", data.interview.map((item) => item.id === topic.id ? { ...item, done: !item.done } : item))} />{topic.name}</label>)}</div></section>}
    </fieldset><section className={styles.team}><div className="panel-heading"><div><span className="eyebrow">YOUR SUPPORTING TOOLS</span><h3>Career AI Team</h3></div></div>{children}</section>
    {(editor || deleting) && <div className={styles.overlay} onKeyDown={(event) => dialogKeyboard(event, close)}><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="career-editor-title"><div className="panel-heading"><h3 id="career-editor-title">{deleting ? "Delete item" : `${editor?.id || editor?.section === "goal" ? "Edit" : "Add"} ${editor?.section}`}</h3><button aria-label="Close" className="text-button" onClick={close}>×</button></div>{error && <p role="alert" className={styles.error}>{error}</p>}{deleting ? <><p>ลบ “{deleting.name}”?</p><div className={styles.actions}><button autoFocus className="secondary-button" onClick={close}>Cancel</button><button className="primary-button" onClick={() => { const { section, id } = deleting; let ok = false; if (section === "applications") ok = save(section, data.applications.filter((item) => item.id !== id)); if (section === "projects") ok = save(section, data.projects.filter((item) => item.id !== id)); if (section === "skills") ok = save(section, data.skills.filter((item) => item.id !== id)); if (section === "resume") ok = save(section, data.resume.filter((item) => item.id !== id)); if (ok) close(); }}>Delete</button></div></> : editor && <form onSubmit={submit}>{fields[editor.section].map((field, index) => <label key={field.key}>{field.label}{field.options ? <select value={editor.values[field.key]} onChange={(e) => setEditor({ ...editor, values: { ...editor.values, [field.key]: e.target.value } })}>{field.options.map((value) => <option key={value}>{value}</option>)}</select> : field.key === "notes" ? <textarea rows={3} maxLength={2000} value={editor.values[field.key]} onChange={(e) => setEditor({ ...editor, values: { ...editor.values, [field.key]: e.target.value } })} /> : <input autoFocus={index === 0} required={field.required} type={field.type ?? "text"} maxLength={field.type === "url" ? 2000 : 200} value={editor.values[field.key]} onChange={(e) => setEditor({ ...editor, values: { ...editor.values, [field.key]: e.target.value } })} />}</label>)}<div className={styles.actions}><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button" type="submit">Save</button></div></form>}</section></div>}
  </div>;
}
