import { useEffect, useRef, useState, type FormEvent } from "react";
import { money, parseAmount, type Entry } from "@/lib/finance";
import { monthlySummary, type FinancePlan } from "@/lib/finance-analytics";
import { closeFinanceMonth, closedMonthSeries, compareScenarios, monthlyReview, simulateScenario, simulationYears, type MonthClose, type MonthReport, type Scenario } from "@/lib/finance-review";
import { dialogKeyboard } from "./dialog-keyboard";
import TrendChart from "./finance-trend-chart";
import styles from "./finance-view.module.css";

const scenarioFields=[ ["name","Scenario name"], ["startingCash","Starting cash"], ["income","Monthly income"], ["expenses","Monthly expenses"], ["savings","Monthly savings"], ["investment","Monthly investment contribution"], ["annualReturn","Expected annual return (%)"], ["inflation","Annual inflation (%)"], ["years","Simulation period"] ] as const;
function scenarioFrom(values:Record<string,string>,id:string):Scenario {
 const moneyValue=(key:string)=>{const value=values[key];const parsed=/^0(?:\.0{1,2})?$/.test(value)?0:parseAmount(value);if(parsed===null)throw Error("Use non-negative amounts with at most two decimal places.");return parsed;};
 return {id,name:values.name.trim(),startingCash:moneyValue("startingCash"),income:moneyValue("income"),expenses:moneyValue("expenses"),savings:moneyValue("savings"),investment:moneyValue("investment"),annualReturn:Number(values.annualReturn),inflation:Number(values.inflation),years:Number(values.years) as Scenario["years"]};
}
function Report({report:r}: {report:MonthReport}) {
 const metrics=[ ["Income",r.income],["Expenses",r.expenses],["Net cash flow",r.netCashFlow],["Savings amount",r.savings],["Investment contribution",r.investmentContribution],["Goal contributions",r.goalContributions],["Average daily spending",r.averageDaily],["Recurring expenses paid",r.recurringPaid] ] as const;
 return <><div className={styles.stats}>{metrics.map(([label,value])=><section className={styles.stat} key={label}><span>{label}</span><strong>{money(value)}</strong></section>)}</div><p>Savings rate: {r.savingsRate.toFixed(1)}%. Savings include positive cash surplus plus tagged investment and goal transfers. Transfers are included in ledger expenses; tags prevent them being lost from retained savings.</p><p>Biggest expense: {r.biggestExpense?`${r.biggestExpense.title} · ${r.biggestExpense.category} · ${money(r.biggestExpense.amount)} · ${r.biggestExpense.date}`:"None"}</p><p>Net worth: {r.netWorth===null?"No snapshot for this month":money(r.netWorth)} · Change: {r.netWorthChange===null?"Requires both monthly net-worth snapshots":money(r.netWorthChange)}</p><p>Compared with {r.previous.month}: Income {money(r.incomeChange)} · Expenses {money(r.expenseChange)} · Savings {money(r.savingsChange)}.</p><div className={styles.analyticsGrid}><section><h4>Top spending categories</h4>{r.categories.slice(0,5).map(c=><p key={c.name}>{c.name} · {money(c.amount)}</p>)}{!r.categories.length&&<p>No expenses.</p>}<h4>Goal contributions</h4>{r.goals.map((g,i)=><p key={i}>{g.name} · {money(g.amount)}</p>)}{!r.goals.length&&<p>No tagged goal contributions. Tag payments in Transactions; editing a goal balance alone is not a payment.</p>}</section><section><h4>Budget vs actual</h4>{r.budgets.map(b=><div key={b.category}><p>{b.category} · Budget {money(b.amount)} · Actual {money(b.spent)} · Remaining {money(b.remaining)}</p>{b.remaining<0&&<p className={styles.expense}>Over budget</p>}</div>)}{!r.budgets.length&&<p>No budgets for this month.</p>}</section></div></>;
}
export function ClosedMonthTrends({plan,endMonth}: {plan:FinancePlan;endMonth:string}) {
 const [count,setCount]=useState(6);const series=closedMonthSeries(plan,endMonth,count);
 return <section><div className={styles.panelHeading}><h3>Closed-month trends</h3><label>Closed history window<select value={count} onChange={e=>setCount(Number(e.target.value))}>{[3,6,12].map(n=><option key={n} value={n}>{n} months</option>)}</select></label></div><p>Uses the latest saved close revision for each month. Unclosed months are omitted, not treated as zero.</p><div className={styles.analyticsGrid}>{([ ["Income","income"], ["Expenses","expenses"], ["Savings rate","savingsRate"], ["Net cash flow","netCashFlow"], ["Net worth","netWorth"] ] as const).map(([title,key])=><TrendChart key={key} title={`Closed ${title.toLowerCase()}`} percent={key==="savingsRate"} points={series.flatMap(s=>s.report&&s.report[key]!==null?[{label:s.month,value:s.report[key]!}]:[])}/>)}</div></section>;
}
export default function FinanceSimulatorReview({mode,plan,entries,month,today,onSave}: {mode:"Simulator"|"Monthly Review";plan:FinancePlan;entries:Entry[];month:string;today:string;onSave:(plan:FinancePlan,entries?:Entry[])=>boolean}) {
 const [draft,setDraft]=useState<{id?:string;values:Record<string,string>;baseline:string}|null>(null);
 const [error,setError]=useState("");const [selected,setSelected]=useState<string[]|null>(null);
 const [history,setHistory]=useState<MonthClose|null>(null);
 const [review,setReview]=useState<{record:MonthReport;month:string;baseline:string;ledger:Entry[];replace:boolean}|null>(null);
 const [confirm,setConfirm]=useState(false);
 const panel=useRef<HTMLElement|null>(null),focus=useRef<HTMLElement|null>(null);
 const modal=!!draft;
 useEffect(()=>{if(!modal)return;panel.current?.querySelector<HTMLElement>("input")?.focus();const overflow=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=overflow;};},[modal]);
 function close(){setDraft(null);setError("");focus.current?.focus();}
 function open(item?:Scenario){focus.current=document.activeElement as HTMLElement;const report=monthlyReview(entries,plan,month,today),summary=monthlySummary(entries,month,today,plan.openingBalance);const s=item??{id:"",name:"Current Plan",startingCash:Math.max(0,summary.cashBalance),income:report.income,expenses:Math.max(0,report.expenses-report.investmentContribution-report.goalContributions),savings:report.goalContributions,investment:report.investmentContribution,annualReturn:0,inflation:0,years:5};setError("");setDraft({id:item?.id,baseline:JSON.stringify(plan),values:Object.fromEntries(scenarioFields.map(([key])=>[key,["name","annualReturn","inflation","years"].includes(key)?String(s[key]):(Number(s[key])/100).toFixed(2)]))});}
 function save(event:FormEvent){event.preventDefault();if(!draft)return;try{if(draft.baseline!==JSON.stringify(plan))throw Error("Scenarios changed elsewhere. Close and reopen the editor.");const scenario=scenarioFrom(draft.values,draft.id??crypto.randomUUID());simulateScenario(scenario);if(onSave({...plan,scenarios:[...plan.scenarios.filter(s=>s.id!==scenario.id),scenario]}))close();else setError("Scenario save failed. Your draft is retained; check the Finance save error.");}catch(e){setError(e instanceof Error?e.message:"Save failed.");}}
 let preview:ReturnType<typeof simulateScenario>|null=null;let previewError="";
 if(draft){try{preview=simulateScenario(scenarioFrom(draft.values,draft.id||"preview"));}catch(e){previewError=e instanceof Error?e.message:"Check inputs.";}}
 const compared=plan.scenarios.filter(s=>selected===null||selected.includes(s.id));
 const baseline=compared[0];
 function beginReview(replace:boolean){setError("");setHistory(null);setConfirm(false);setReview({record:monthlyReview(entries,plan,month,today),month,baseline:JSON.stringify(plan),ledger:JSON.parse(JSON.stringify(entries)),replace});}
 const existing=plan.closes.filter(c=>c.month===month).at(-1);
 const report=review?.record??history?.report??monthlyReview(entries,plan,month,today);
 return <section className={styles.analyticsBody}>
 {error&&<p role="alert" className={styles.error}>{error}</p>}
 {mode==="Simulator"?<>
  <section className={styles.panel}><div className={styles.panelHeading}><h3>Financial Scenario Simulator</h3><button className="primary-button" onClick={()=>open()}>+ Add scenario</button></div><p>Estimates, not guaranteed returns. Monthly contributions are paid at month end; annual return is converted to an equivalent monthly compound rate. Income and expenses stay fixed in nominal THB. Inflation adjusts final purchasing power. Savings earn no interest. No market data or AI is used.</p><p>Monthly savings and investments are allocations from income, not extra income. Any remaining surplus stays in cash. A deficit is shown as negative cash; the simulation still assumes contributions continue.</p><div className={styles.scenarioSelectors}>{plan.scenarios.map(s=><label key={s.id}><input type="checkbox" checked={selected===null||selected.includes(s.id)} onChange={()=>{const current=selected===null?plan.scenarios.map(s=>s.id):selected;setSelected(current.includes(s.id)?current.filter(id=>id!==s.id):[...current,s.id]);}}/>{s.name}</label>)}</div></section>
  {!plan.scenarios.length&&<p className={styles.empty}>No scenarios yet. Add Current Plan, Higher Saving or Higher Investment to compare assumptions.</p>}
  <div className={styles.scenarioGrid}>{compared.map(s=>{const result=simulateScenario(s),delta=baseline?compareScenarios(baseline,s):null;return <article className={styles.analyticsCard} key={s.id}><h4>{s.name} · {s.years} years</h4><p>Projected wealth: <strong>{money(result.final.wealth)}</strong></p><p>Investment value {money(result.final.investment)} · investment growth {money(result.final.growth)}</p><p>Cash {money(result.final.cash)} · savings {money(result.final.savings)} · combined {money(result.final.cash+result.final.savings)}</p><p>Total contributions {money(result.final.contributions)} · investment contributions {money(result.final.investmentContributions)}</p><p>Purchasing power {money(result.final.purchasingPower)}</p><p>Savings rate {result.savingsRate.toFixed(1)}% · Investment rate {result.investmentRate.toFixed(1)}%</p>{result.monthlyUnallocated<0&&<p className={styles.expense}>Monthly allocations exceed disposable income by {money(-result.monthlyUnallocated)}.</p>}{delta&&<p>Versus {baseline?.name}: final wealth {money(delta.wealth)} · contributions {money(delta.contributions)} · growth {money(delta.growth)}.{s.years!==baseline?.years&&" Different horizons: results are not like-for-like."}</p>}<div className={styles.actions}><button className="secondary-button" onClick={()=>open(s)}>Edit scenario</button><button className="text-button" onClick={()=>{onSave({...plan,scenarios:[...plan.scenarios,{...s,id:crypto.randomUUID(),name:`${s.name.slice(0,110)} copy`}]});}}>Duplicate</button><button className={styles.delete} onClick={()=>{if(window.confirm(`Delete scenario “${s.name}”?`))onSave({...plan,scenarios:plan.scenarios.filter(item=>item.id!==s.id)});}}>Delete scenario</button></div><TrendChart title={`${s.name} yearly wealth`} points={result.yearly.map(y=>({label:`Year ${y.year}`,value:y.wealth}))}/><details><summary>Yearly progression</summary><div className={styles.dataScroll}><table className={styles.dataTable}><thead><tr>{["Year","Contributions","Investment","Cash","Savings","Wealth","Purchasing power"].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{result.yearly.map(y=><tr key={y.year}><th scope="row">{y.year}</th>{[y.contributions,y.investment,y.cash,y.savings,y.wealth,y.purchasingPower].map((value,i)=><td key={i}>{money(value)}</td>)}</tr>)}</tbody></table></div></details></article>;})}</div>
 </>:<>
  <section className={styles.panel}><div className={styles.panelHeading}><h3>{review?`Review before closing · ${review.month}`:history?`Historical close · ${history.month}`:`Monthly Review · ${month}`}</h3>{!review&&!history&&<button className="primary-button" disabled={month>today.slice(0,7)} onClick={()=>beginReview(!!existing)}>{existing?"Review replacement":"Close Month"}</button>}{history&&<button className="secondary-button" onClick={()=>setHistory(null)}>Back to live review</button>}</div><p>{history?`Saved ${history.closedAt}. Values and labels are frozen.`:review?"Review these values before saving. Transactions will not be modified.":"Live review from saved transactions. Future-dated transactions are excluded. Tag investment and saving-goal transfers in Transactions."}</p>{month===today.slice(0,7)&&!history&&<p>This is a partial month through {today}. Closing now freezes this month-to-date report.</p>}<Report report={report}/>
  {review&&<><label className={styles.reviewConfirm}><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>{review.replace?"I confirm replacing this month's close with a new revision. Earlier revisions will remain available.":"I have reviewed this report and confirm closing the month."}</label><div className={styles.actions}><button className="secondary-button" onClick={()=>setReview(null)}>Cancel review</button><button className="primary-button" disabled={!confirm} onClick={()=>{try{if(review.baseline!==JSON.stringify(plan)||JSON.stringify(review.ledger)!==JSON.stringify(entries))throw Error("Finance data changed during review. Cancel and review again.");const next=closeFinanceMonth(plan,review.ledger,review.month,new Date().toISOString(),review.replace);if(onSave(next,review.ledger)){setReview(null);setHistory(next.closes.at(-1)!);}}catch(e){setError(e instanceof Error?e.message:"Close failed.");}}}>Save close</button></div></>}
  </section><section className={styles.panel}><h3>Closed months & revisions</h3>{!plan.closes.length&&<p className={styles.empty}>No closed months yet. Review a month before saving its report.</p>}<div className={styles.closeHistory}>{[...plan.closes].sort((a,b)=>b.month.localeCompare(a.month)||b.closedAt.localeCompare(a.closedAt)).map(c=><button className="secondary-button" key={c.id} onClick={()=>{setHistory(c);setReview(null);setError("");}}>{c.month} · revision {plan.closes.filter(s=>s.month===c.month).findIndex(s=>s.id===c.id)+1} · {c.closedAt.slice(0,10)}</button>)}</div></section><ClosedMonthTrends plan={plan} endMonth={month}/>
 </>}
 {draft&&<div className={styles.overlay} onKeyDown={event=>dialogKeyboard(event,close)}><section ref={panel} className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="finance-scenario-title"><div className={styles.panelHeading}><h3 id="finance-scenario-title">{draft.id?"Edit":"Add"} scenario</h3><button aria-label="Close scenario editor" onClick={close}>×</button></div><form onSubmit={save}>{scenarioFields.map(([key,label])=><label key={key}>{label}{key==="years"?<select value={draft.values.years} onChange={e=>setDraft({...draft,values:{...draft.values,years:e.target.value}})}>{simulationYears.map(n=><option key={n} value={n}>{n} {n===1?"year":"years"}</option>)}</select>:<input autoFocus={key==="name"} required maxLength={key==="name"?120:20} inputMode={key==="name"?undefined:"decimal"} value={draft.values[key]} onChange={e=>setDraft({...draft,values:{...draft.values,[key]:e.target.value}})}/>}</label>)}{preview?<div role="status"><p>Live estimate: {money(preview.final.wealth)} wealth · {money(preview.final.purchasingPower)} purchasing power.</p><p>Investment growth {money(preview.final.growth)} · cash {money(preview.final.cash)} · savings {money(preview.final.savings)}.</p>{preview.monthlyUnallocated<0&&<p className={styles.expense}>Allocations exceed monthly income. Cash will fall.</p>}</div>:<p role="status">{previewError}</p>}{error&&<p role="alert" className={styles.error}>{error}</p>}<div className={styles.actions}><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button" type="submit" disabled={!preview}>Save scenario</button></div></form></section></div>}
 </section>;
}
