import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import path from 'node:path';
const root=path.resolve('data/uploads');
const types:Record<string,string>={'application/pdf':'pdf','image/png':'png','image/jpeg':'jpg','image/webp':'webp'};
export async function POST(req:Request){
 if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return new Response('Forbidden',{status:403});
 try{if(Number(req.headers.get('content-length'))>11*1024*1024)throw Error('ไฟล์ใหญ่เกิน 10 MB');const form=await req.formData();const file=form.get('file');if(!(file instanceof File)||!types[file.type]||file.size>10*1024*1024)throw Error('รองรับ PDF, PNG, JPEG, WebP ไม่เกิน 10 MB');const bytes=Buffer.from(await file.arrayBuffer());const valid=file.type==='application/pdf'?bytes.subarray(0,5).toString()==='%PDF-':file.type==='image/png'?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):file.type==='image/jpeg'?bytes[0]===255&&bytes[1]===216:bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP';if(!valid)throw Error('เนื้อหาไฟล์ไม่ตรงกับชนิดไฟล์');const name=`${randomUUID()}.${types[file.type]}`;await mkdir(root,{recursive:true});await writeFile(path.join(root,name),bytes,{flag:'wx'});return Response.json({name});}catch(e){return Response.json({error:e instanceof Error?e.message:'อัปโหลดไม่สำเร็จ'},{status:400});}
}
export async function GET(req:Request){const name=new URL(req.url).searchParams.get('name')||'';if(!/^[a-f0-9-]{36}\.(pdf|png|jpg|webp)$/.test(name))return new Response('Not found',{status:404});try{const data=await readFile(path.join(root,name));const ext=name.split('.').pop();return new Response(data,{headers:{'Content-Type':Object.entries(types).find(([,v])=>v===ext)?.[0]||'application/octet-stream','Content-Disposition':`inline; filename="${name}"`,'X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox"}});}catch{return new Response('Not found',{status:404});}}
